#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Feb 27 01:28:46 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=15
shaderPack=ComplementaryReimagined_r5.7.1.zip
